### Automatic Document Clustering

In [1]:
import pandas as pd
import numpy as np

#### a. Create your own distance function that, instead of using Euclidean distance, uses Cosine similarity.

In [2]:
def disCosine(x, D):
    D_norm = np.linalg.norm(D)
    x_norm = np.linalg.norm(x)
    sims = np.dot(D,x)/(D_norm * x_norm)
    dists = 1- sims
    return dists

#### b. Load the data set, Then, split the data set (the document x term matrix) and set aside 20% for later use (see below). Use the 80% segment for clustering in the next part. The 20% portion must be a random subset.

In [3]:
### load data
DT = pd.read_csv('/Users/Alexkilledme/Desktop/2018SQ/CSC478 - Machine Learning/hw/newsgroups5/matrix.txt',sep=',',header=None)
DT = np.array(DT.T)
Terms = pd.read_csv('/Users/Alexkilledme/Desktop/2018SQ/CSC478 - Machine Learning/hw/newsgroups5/terms.txt',sep=' ',header=None)
Terms = np.array(Terms)
Class = pd.read_csv('/Users/Alexkilledme/Desktop/2018SQ/CSC478 - Machine Learning/hw/newsgroups5/classes.txt',sep=' ')
Class = Class.iloc[:,1]
Class = np.array(Class)

In [4]:
print DT
print DT.shape

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(2500, 9328)


In [5]:
print Terms
print Terms.shape

[['aa']
 ['aargh']
 ['aaron']
 ...
 ['zw']
 ['zx']
 ['zz']]
(9328, 1)


In [6]:
print Class
print Class.shape

[0 1 1 ... 3 4 2]
(2500,)


In [7]:
N_doc_train=DT.shape[0]
N_terms=Terms.shape[0]
print('There are ',N_doc_train,'documents')
print('There are ',N_terms,'terms')

('There are ', 2500, 'documents')
('There are ', 9328, 'terms')


In [8]:
### split training and testing data
from sklearn.cross_validation import train_test_split
DT_train, DT_test, Class_train, Class_test = train_test_split(DT, Class, test_size=0.2, random_state=33)

/Users/Alexkilledme/anaconda2/lib/python2.7/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [9]:
print DT_train.shape
print DT_test.shape
print Class_train.shape
print Class_test.shape

(2000, 9328)
(500, 9328)
(2000,)
(500,)


#### c. Perform Kmeans clustering on the training data. Write a function to display the top N terms in each cluster along with the cluster DF values for each term and the size of the cluster. The cluster DF value for a term t in a cluster C is the percentage of docs in cluster C in which term t appears (so, if a cluster has 500 documents, and term "game" appears in 100 of those 500 documents, then DF value of "game" in that cluster is 0.2 or 20%). Sort the terms for each cluster in decreasing order of the DF percentage. Here is an example of how this output might look like (here the top 10 terms for 3 of the 5 clusters are displayed in decreasing order of cluster DF values, but the mean frequnecy from the cluster centroid is also shown). [Extra Credit: use your favorite third party tool, ideally with a Python based API, to create a word cloud for each cluster.]

In [10]:
#convert the data into TFIDF is using sklearn.feature_extraction.text built-in module

from sklearn.feature_extraction.text import TfidfTransformer
NewDTTrain_TFIDF = TfidfTransformer().fit_transform(DT_train).toarray()
NewDTTest_TFIDF = TfidfTransformer().fit_transform(DT_test).toarray()

In [11]:
### Perform Kmeans clustering on the training data

In [12]:
cd "/Users/Alexkilledme/Desktop/"

/Users/Alexkilledme/Desktop


In [13]:
from numpy import *
from sklearn.cluster import KMeans 
import kMeans

In [14]:
reload(kMeans)

<module 'kMeans' from 'kMeans.pyc'>

In [15]:
#D = input Dataset
#k = Number of Clusters
#Measure = disCosine or disEuclid
#top_No_terms = Number of terms in each cluster will be displayed

#kMeans_func is used to display the top N terms in each cluster along with
#the cluster DF values for each term and percent of Docs include the term.
def TopTerms(data, k, NTerms):
    centroids, clusters = kMeans.kMeans(mat(data), k, distMeas=disCosine)
    for i in range(k):
        print 'cluster',i+1,':'
        cluster_DT = data[clusters[:,0]==i]
        print 'cluster',i+1,' size: ', cluster_DT.shape[0]
        cluster_DF = np.array([(cluster_DT.T!=0).sum(1)]).T
        term_doc_pc_cluster = cluster_DF/float(cluster_DT.shape[0])
        term_doc_pc_cluster = map(list, term_doc_pc_cluster)
        term_doc_pc_cluster = [elem[0] for elem in term_doc_pc_cluster]
        cluster_DF = [elem[0] for elem in cluster_DF]
        a=sorted(zip(Terms, cluster_DF, term_doc_pc_cluster),key=lambda x:x[2],reverse=True)
        for elem in a[:NTerms]:
            print 'term: ',elem[0]
            print 'cluster DF: ',elem[1]
            print 'percentage of docs in the cluster where the term appears: ',elem[2],'\n'
        print '\n'
    return  centroids, clusters

In [16]:
centroids, clusters = TopTerms(NewDTTrain_TFIDF, 5, 3)

cluster 1 :
cluster 1  size:  382
term:  ['subject']
cluster DF:  382
percentage of docs in the cluster where the term appears:  1.0 

term:  ['write']
cluster DF:  262
percentage of docs in the cluster where the term appears:  0.6858638743455497 

term:  ['articl']
cluster DF:  201
percentage of docs in the cluster where the term appears:  0.5261780104712042 



cluster 2 :
cluster 2  size:  401
term:  ['subject']
cluster DF:  401
percentage of docs in the cluster where the term appears:  1.0 

term:  ['write']
cluster DF:  219
percentage of docs in the cluster where the term appears:  0.5461346633416458 

term:  ['game']
cluster DF:  214
percentage of docs in the cluster where the term appears:  0.5336658354114713 



cluster 3 :
cluster 3  size:  392
term:  ['subject']
cluster DF:  392
percentage of docs in the cluster where the term appears:  1.0 

term:  ['window']
cluster DF:  277
percentage of docs in the cluster where the term appears:  0.7066326530612245 

term:  ['write']
clu

#### d. Using the cluster assignments from Kmeans clustering, compare your 5 clusters to the 5 pre-assigned classes by computing the Completeness and Homogeneity values.

In [26]:
### split training and testing data
from sklearn.cross_validation import train_test_split
DT_train, DT_test, Class_train, Class_test = train_test_split(DT, Class, test_size=0.2, random_state=33)

In [27]:
clusters.T[0].shape

(2000,)

In [28]:
Class_train.shape

(2000,)

In [29]:
from sklearn.metrics import completeness_score, homogeneity_score
predict_Class_train_=clusters.T[0]
print('Completenness Score is ',completeness_score(Class_train , predict_Class_train_))
print('Homogeneity Score is ',homogeneity_score(Class_train , predict_Class_train_))

('Completenness Score is ', 0.831410599743451)
('Homogeneity Score is ', 0.831255162573729)


Baed on the result, the completenness score is quite high which means that most of the data points are members of a given class are assigned to the same cluster. The Homogeneity Score are as high as the completenness score. In this case, it represent about 83.7% of clusters do not only contain the members of data points belong to one Single cluster.

#### e. Finally, using your cluster assignments as class labels, categorize each of the documents in the 20% set-aside data into each of the appropriate cluster. Your categorization should be based on Cosine similarity between each test document and cluster centroids. For each test document show the predicted class label as well as Cosine similarity to the corresponding cluster.

In [30]:
records = []
for test_doc in NewDTTest_TFIDF:
    dic = {}
    sim = []
    cluster=1
    for centroid in centroids:
        sim.append(1-disCosine(test_doc, centroid)) 
        dic['Similarity With Cluster '+str(cluster)] = 1 - disCosine(test_doc, centroid)
        cluster+=1
    dic['Cluster Assignment'] = sim.index(max(sim))+1
    records.append(dic)
test_cluster = pd.DataFrame(records,index=range(len(NewDTTest_TFIDF)),columns=['Similarity With Cluster 1','Similarity With Cluster 2',
                                                                             'Similarity With Cluster 3','Similarity With Cluster 4',
                                                                             'Similarity With Cluster 5', 'Cluster Assignment'])
test_cluster.head(10)

Similarity With Cluster 1  Similarity With Cluster 2  \
0                   0.060551                   0.045611   
1                   0.101560                   0.065623   
2                   0.033958                   0.025975   
3                   0.132757                   0.109677   
4                   0.026766                   0.093297   
5                   0.436565                   0.103924   
6                   0.128532                   0.332148   
7                   0.074624                   0.049821   
8                   0.119753                   0.105476   
9                   0.053651                   0.064825   

   Similarity With Cluster 3  Similarity With Cluster 4  \
0                   0.045606                   0.148978   
1                   0.063095                   0.162041   
2                   0.023437                   0.037503   
3                   0.296690                   0.136764   
4                   0.033020                   0.059599   
5                   0.112584                   0.125249   
6                   0.101132                   0.134792   
7                   0.057916                   0.090390   
8                   0.097094                   0.464692   
9                   0.054491                   0.128654   

   Similarity With Cluster 5  Cluster Assignment  
0                   0.042910                   4  
1                   0.082199                   4  
2                   0.106480                   5  
3                   0.105167                   3  
4                   0.207182                   5  
5                   0.109056                   1  
6                   0.094342                   2  
7                   0.096512                   5  
8                   0.093785                   4  
9                   0.041227                   4

In [31]:
test_cluster.to_csv('test_cluster.csv', sep=",")